server.port=8899
spring.application.name=service-resenas

spring.datasource.url=jdbc:mysql://localhost:3306/db_resenas
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update