server.port=8088
spring.application.name=service-logistica

# Conexión a DB Logística
spring.datasource.url=jdbc:mysql://localhost:3306/db_logistica?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Sincronización de tablas sin borrar datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true